Do not let the test browser handle errors.  Fix getting RichText output.
I want to see the actual error, instead of just getting a 500 Internal Server Error.
Now we get this error, which we fix in this same commit:

```
File "/Users/maurits/tmp/collective.watcherlist/collective/watcherlist/sample/newsletter.txt", line 107, in newsletter.txt
Failed example:
    browser.open(news.first.absolute_url() + '/@@newsitem-mail')
Exception raised:
    Traceback (most recent call last):
      File "/Users/maurits/.pyenv/versions/3.11.7/lib/python3.11/doctest.py", line 1353, in __run
        exec(compile(example.source, filename, "single",
      File "<doctest newsletter.txt[26]>", line 1, in <module>
        breakpoint(); browser.open(news.first.absolute_url() + '/@@newsitem-mail')
      File "/Users/maurits/tmp/collective.watcherlist/.tox/test/lib/python3.11/site-packages/zope/testbrowser/browser.py", line 252, in open
        self._processRequest(url, make_request)
      File "/Users/maurits/tmp/collective.watcherlist/.tox/test/lib/python3.11/site-packages/zope/testbrowser/browser.py", line 278, in _processRequest
        resp = make_request(reqargs)
      File "/Users/maurits/tmp/collective.watcherlist/.tox/test/lib/python3.11/site-packages/zope/testbrowser/browser.py", line 249, in make_request
        return self.testapp.get(url, **args)
      File "/Users/maurits/tmp/collective.watcherlist/.tox/test/lib/python3.11/site-packages/webtest/app.py", line 324, in get
        return self.do_request(req, status=status,
      File "/Users/maurits/tmp/collective.watcherlist/.tox/test/lib/python3.11/site-packages/zope/testbrowser/browser.py", line 92, in do_request
        response = super().do_request(req, status,
      File "/Users/maurits/tmp/collective.watcherlist/.tox/test/lib/python3.11/site-packages/webtest/app.py", line 620, in do_request
        res = req.get_response(app, catch_exc_info=True)
      File "/Users/maurits/tmp/collective.watcherlist/.tox/test/lib/python3.11/site-packages/webob/request.py", line 1309, in send
        status, headers, app_iter, exc_info = self.call_application(
      File "/Users/maurits/tmp/collective.watcherlist/.tox/test/lib/python3.11/site-packages/webob/request.py", line 1278, in call_application
        app_iter = application(self.environ, start_response)
      File "/Users/maurits/tmp/collective.watcherlist/.tox/test/lib/python3.11/site-packages/webtest/lint.py", line 196, in lint_app
        iterator = application(environ, start_response_wrapper)
      File "/Users/maurits/tmp/collective.watcherlist/.tox/test/lib/python3.11/site-packages/plone/testing/_z2_testbrowser.py", line 36, in wrapped_func
        return func(*args, **kw)
      File "/Users/maurits/tmp/collective.watcherlist/.tox/test/lib/python3.11/site-packages/plone/testing/_z2_testbrowser.py", line 63, in __call__
        wsgi_result = publish(environ, start_response)
      File "/Users/maurits/tmp/collective.watcherlist/.tox/test/lib/python3.11/site-packages/ZPublisher/WSGIPublisher.py", line 391, in publish_module
        response = _publish(request, new_mod_info)
      File "/Users/maurits/tmp/collective.watcherlist/.tox/test/lib/python3.11/site-packages/ZPublisher/WSGIPublisher.py", line 285, in publish
        result = mapply(obj,
      File "/Users/maurits/tmp/collective.watcherlist/.tox/test/lib/python3.11/site-packages/ZPublisher/mapply.py", line 98, in mapply
        return debug(object, args, context)
      File "/Users/maurits/tmp/collective.watcherlist/.tox/test/lib/python3.11/site-packages/ZPublisher/WSGIPublisher.py", line 68, in call_object
        return obj(*args)
      File "/Users/maurits/tmp/collective.watcherlist/collective/watcherlist/browser.py", line 54, in __call__
        return self.html
      File "/Users/maurits/tmp/collective.watcherlist/collective/watcherlist/sample/browser.py", line 18, in html
        return text.output()
    TypeError: 'str' object is not callable
```